# Generated by Django 4.2.9 on 2024-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
